name: Linting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  rdflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - uses: imas/setup-rdflint@v1
    - run: rdflint
